### ISSUE TITLE
select选项框最大宽度限制优化

### ISSUE THREAD

**Issue by jktantan** [EOITek/element#42]
当前版本有option-max-width，来限制选项框的最大宽度。限制类型只有`不限制`和`以配置为主`两种。
其实还有另一种也是最常用的，就是`选项框的最大宽度与显示框宽度一致`，在这种情况下，选项框应该是每次显示前都先确认一下显示框宽度是多少，再显示。

**Comment by CarterLi** [comment]
直接把选项框和显示框的宽度都定死不好么？我觉得用处不大

**Comment by jktantan** [comment]
> 直接把选项框和显示框的宽度都定死不好么？我觉得用处不大

还真不行。。。。政事单位里面的显示器从老到新，从小到大什么都有。想要适配就必须使用自动适配，这也导致了宽度就根本没法确定下来。而且旧有样式中，我记得select框的宽度一直都是跟着主框变的，不知道为何到了VUE这个时代，有很多很好的样式设计都给放弃了。

**Comment by jktantan** [comment]
动态宽度和动态高度问题，在更新popper2之后解决，官方本来就有解决方案
