### ISSUE TITLE
select选项框高度优化

### ISSUE THREAD

**Issue by jktantan** [EOITek/element#43]
select 选项框高度现在应该只有固定高度或者只能配置一个定死的高度。
实际情况特别是政企项目来说，由于选项框内的内容有可能有很多，所以他们是希望尽可能多的显示数据。这就需要有以下几点优化：
1. 除了默认高度和可配置高度，应该可以配置一个自适应高度
2. 显示下拉框的时候如果数据量或者应显示的高度超限时，判断上方和下方哪个方向能显示更多内容再弹出选项框且选项框不超屏幕。

**Comment by CarterLi** [comment]
第一个应该好做
第二个应该现有的select就能做到

**Comment by jktantan** [comment]
> 第一个应该好做
> 第二个应该现有的select就能做到

恩，第二个原本就有，就是配合第一点的时候，原element-ui的方法可能会要有相应的修改。

**Comment by CarterLi** [comment]
@jktantan 我看了一下，max-height是在scss里面指定的，而且有用变量

https://github.com/EOITek/element/blob/dev/packages/theme-chalk/src/select-dropdown.scss#L51

你只需要全局指定 `$--select-dropdown-max-height: unset` 应该就可以

**Comment by CarterLi** [comment]
Closed for inactivity
