### ISSUE TITLE
级联选择器选项框的宽度和高度优化

### ISSUE THREAD

**Issue by jktantan** [EOITek/element#44]
和select选项框一样，级联选择器的宽度也应该有个限宽。高度也应该可以有自适应高度

**Comment by CarterLi** [comment]
可以。我们公司级联选择器很少用所以没太关注

**Comment by CarterLi** [comment]
级联选择器高度很难自适应，内部实现依赖外部定高

**Comment by CarterLi** [comment]
Closed for inactivity
