### ISSUE TITLE
element官方已经凉了来围观下这个fork

### ISSUE THREAD

**Issue by scvzerng** [EOITek/element#74]
emmm element官方人已经跑完了不知道这个分支还能坚持多久

**Comment by CarterLi** [comment]
会坚持到我们公司不用element为止

**Comment by scvzerng** [comment]
加油

**Comment by kooriookami** [comment]
> emmm element官方人已经跑完了不知道这个分支还能坚持多久

关注下https://github.com/element-plus/element-plus
